#-----------------------------------------------

theme:
  primary: "blue"
  accent: "blue-grey"

language:
  default:
    key: "en"
    value: "English"
  extra: false

services: true
scrollTop: true
sync: true

config:
  icon: "icons/agneta/logo"
  title: true

colors:
  primary: "#116477"
  accent: "#899ea3"
  primary-darker: "#0b4c5b"

#-----------------------------------------------

account:
  register: false
  menu: null

#-----------------------------------------------

page:
  viewBase:
    local: "private/page-local"
    default: "private/page"

media:
  storageRoot: "page"
  base: "private/media"

#-----------------------------------------------

minify:
  html: true
  css: true
  js: true

#-----------------------------------------------

cookies: true
search: true
languages_toolbar: false
languages_sidebar: false
languages_footer: true

#-----------------------------------------------

scripts:
  lib:
    - "lib/angular.min"
    - path: "lib/angular-aria.min"
    - path: "lib/angular-animate.min"
    - dep: "ngMessages"
      path: "lib/angular-messages.min"
    - dep: "ngMaterial"
      path: "lib/angular-material.min"
    - dep: "ngResource"
      path: "lib/angular-resource.min"
    - dep: "oc.lazyLoad"
      path: "lib/ocLazyLoad.min"
    - dep: "ngRoute"
      path: "lib/angular-route.min"
    - dep: "ngSanitize"
      path: "lib/angular-sanitize.min"
    - dep: "ngStorage"
      path: "lib/ngStorage.min"
    - name: io
      path: "lib/socket.io"
  app:
    - dep: lbServices
      path: generated/services.min
    - "main"

#-----------------------------------------------

libraries:
  ngQuill:
    ignoreDefaults: true
    include:
      - "src/ng-quill.js"
  quill.tar:
    include:
      - "quill.snow.css"
      - "quill.min.js"
  codemirror:
    dir: "editor"
    include:
      - "addon/lint/lint.js"
      - "addon/lint/lint.css"
      - "addon/lint/yaml-lint.js"
      - "mode/yaml/yaml.js"
      - "mode/javascript/javascript.js"
      - "keymap/sublime.js"
      - "theme/monokai.css"
      - "lib/**"
  st-json-beautifier:
    include: "*.{css,min.js}"
  videogular-themes-default:
    include:
      - "fonts/**"
      - "*.min.css"
  fuse.js:
    ignoreDefaults: true
    include: "*.min.js"
  angular-i18n:
    dir: "angular-i18n"
    include:
      - "angular-locale_**.js"
  angular-material-sidemenu:
    include:
      - "dest/**"
  angular-material:
    ignore:
      - "modules/**"
      - "layouts/**"
  socket.io-client:
    include:
      - dist/**
  zxcvbn:
    include:
      - dist/socket.io.js
      - dist/socket.io.js.map
  moment:
    dir: "moment"
    include: "*.js"
    ignore:
      - "ender.js"
      - "moment.js"
      - "package.js"
  Swiper:
    ignore:
      - "**/*.jquery.**"
  photoswipe:
    dir: "photoswipe"
    include: "*.{css,min.js,svg}"
